# Generated by Django 5.2.1 on 2025-06-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSE', models.CharField(max_length=100)),
                ('BBA', models.IntegerField()),
                ('MATH', models.TextField()),
                ('english', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tacher_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('tacher_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
